## Day 15: Unsupervised Learning & User Segmentation

In [16]:
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
import numpy as np

X, _ = make_blobs(n_samples=300, centers=5, cluster_std=0.60, random_state=0)

# Scale the data 
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [17]:
# Run 1: Random Init
kmeans_random1 = KMeans(n_clusters=5, init='random', random_state=42, n_init=10)
kmeans_random1.fit(X_scaled)

# Run 2: Random Init (different seed)
kmeans_random2 = KMeans(n_clusters=5, init='random', random_state=7, n_init=10)
kmeans_random2.fit(X_scaled)

# Run 3: K-Means++
kmeans_plus = KMeans(n_clusters=5, init='k-means++', random_state=42, n_init=10)
kmeans_plus.fit(X_scaled)

# Store centers
centers_1 = kmeans_random1.cluster_centers_
centers_2 = kmeans_random2.cluster_centers_
centers_3 = kmeans_plus.cluster_centers_

print("Random Init (Run 1):\n", centers_1)
print("\nRandom Init (Run 2):\n", centers_2)
print("\nK-Means++:\n", centers_3)

Random Init (Run 1):
 [[-0.89061023  0.06183114]
 [-0.78233544  1.457609  ]
 [-0.22138319  0.49748257]
 [ 0.04271081 -0.53634677]
 [ 1.85161805 -1.48057593]]

Random Init (Run 2):
 [[-0.22138319  0.49748257]
 [ 1.85161805 -1.48057593]
 [-0.78233544  1.457609  ]
 [ 0.04271081 -0.53634677]
 [-0.89061023  0.06183114]]

K-Means++:
 [[-0.89061023  0.06183114]
 [ 1.85161805 -1.48057593]
 [-0.78233544  1.457609  ]
 [ 0.04271081 -0.53634677]
 [-0.22138319  0.49748257]]


In [18]:
# Measure difference between cluster centers
diff_1_2 = np.linalg.norm(centers_1 - centers_2)
diff_1_3 = np.linalg.norm(centers_1 - centers_3)

print("Difference (Random1 vs Random2):", diff_1_2)
print("Difference (Random1 vs KMeans++):", diff_1_3)

Difference (Random1 vs Random2): 5.229115066803688
Difference (Random1 vs KMeans++): 5.001719845485334


## REFLECTION:

If we find a group of users who like late - night events and high intensity sports, it basically tells us that they are more engaged during night , so instead of giving them general recommendations, the Mux AI glass can become more personalised and relevant to their habits.
For example : 
- AI glass can highlight nearby places or events happening at night.
- Suggest connections with similar users in the same cluster, enabling group activities or shared experiences.
clustering helps us understand “what kind of person the user is,” and then the AI Glass uses that understanding to give smarter, more useful, and more personalized suggestions instead of random ones.